# Generated by Django 2.2.5 on 2019-09-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universos', '0001_initial'),
        ('habilidades', '0001_initial'),
        ('hab_heroi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroi',
            name='hab_heroi',
        ),
        migrations.AddField(
            model_name='heroi',
            name='hab_heroi',
            field=models.ManyToManyField(related_name='hab_heroi', to='habilidades.Habilidades'),
        ),
        migrations.RemoveField(
            model_name='heroi',
            name='uni_heroi',
        ),
        migrations.AddField(
            model_name='heroi',
            name='uni_heroi',
            field=models.ManyToManyField(related_name='univer_heroi', to='universos.Universos'),
        ),
    ]
