# Generated by Django 2.2.5 on 2019-09-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilidades', '0001_initial'),
        ('universos', '0001_initial'),
        ('ark_vilao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vilao',
            name='hab_vilao',
        ),
        migrations.AddField(
            model_name='vilao',
            name='hab_vilao',
            field=models.ManyToManyField(related_name='hab_vilao', to='habilidades.Habilidades'),
        ),
        migrations.RemoveField(
            model_name='vilao',
            name='uni_vilao',
        ),
        migrations.AddField(
            model_name='vilao',
            name='uni_vilao',
            field=models.ManyToManyField(related_name='univer_vilao', to='universos.Universos'),
        ),
    ]
